// Code generated by Kitex v0.8.0. DO NOT EDIT.

package taskservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"todolist/idl/task/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetTaskList(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskListResponse, err error)
	GetTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error)
	CreateTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error)
	UpdateTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error)
	DeleteTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTaskServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTaskServiceClient struct {
	*kClient
}

func (p *kTaskServiceClient) GetTaskList(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTaskList(ctx, req)
}

func (p *kTaskServiceClient) GetTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTask(ctx, req)
}

func (p *kTaskServiceClient) CreateTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTask(ctx, req)
}

func (p *kTaskServiceClient) UpdateTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTask(ctx, req)
}

func (p *kTaskServiceClient) DeleteTask(ctx context.Context, req *api.TaskRequest, callOptions ...callopt.Option) (r *api.TaskDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTask(ctx, req)
}
